export type GuideRow = {
  id: string;
  name: string | null;
  email: string | null;
  approved: boolean | null;
  countries: string | null;
  experience: string | null;
  created_at: string | null;
  languages: string | null;
  description: string | null;
  photograph: string | null;
  user_id: string | null;
  is_approved: boolean | null;
  is_admin: boolean | null;
  profile_image: string | null;
  destination: string | null;
  focus: string | null;
  rating: number | null;
  continent: string | null;
  content: string | null;
};
